name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  lint-and-dedupe:
    runs-on: ubuntu-latest

    name: Lint & Deduplicate deps on node 12.x and ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Install deps and build (with cache)
        run: yarn install && yarn build

      - name: Lint codebase
        run: yarn lint:post-build

#       - name: Deduplicate dependencies
#         run: yarn deduplicate:check

  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ["16.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            node: "12.x"
          - os: ubuntu-latest
            node: "14.x"
          - os: ubuntu-latest
            node: "17.x"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        run: yarn install && yarn build


      - name: Test package
        run: yarn test:post-build
