name: Node CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  lint-and-dedupe:
    runs-on: ubuntu-latest

    name: Lint & Deduplicate deps on node 18.x and ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: npm latest
        run: npm i -g npm@latest

      - name: Install deps and build (with cache)
        run: npm install && npm run build

      - name: Lint codebase
        run: npm run lint:post-build

  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            node: '14.x'
          - os: ubuntu-latest
            node: '16.x'
          - os: ubuntu-latest
            node: '19.x'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: npm latest
        run: npm i -g npm@latest

      - name: Install deps and build (with cache)
        run: npm install && npm run build

      - name: Test package
        run: npm run test:post-build
